### ISSUE TITLE
Rotation of tiles

### ISSUE THREAD

**Issue by TheLethalGoose** [ironcutter24/TiledCS-example-MonoGame#1]
I worked with your example and noticed that rotating tiles by 90° is not catched in your Draw method. Using IsTileFlippedDiagonal() detects the right tile, but adjusting the rotation param of the draw method, leads to a shifted tile.
Any idea for good solution?

**Comment by icutter** [comment]
Draw method takes a rotation in radians and the rotation happens around the upper-left corner of each sprite, so you should account for that in the destinationRectangle parameter.
I'm going to update the example with this functionality as soon as I can, thanks for pointing it out!

**Comment by TheLethalGoose** [comment]
Great :) Thank you for your example project!

**Comment by icutter** [comment]
You are welcome!

**Comment by TheLethalGoose** [comment]
`                    if (map.IsTileFlippedDiagonal(layer, x, y))
                    {
                        rotation = ((float) Math.PI / 2.0f);
                        destination.X += map.TileWidth;
                    }`

Mostly did the job. But i'm having troubles to find a satisfying solution if the tile was flipped additionally.

**Comment by icutter** [comment]
I don't think that is a solution: a diagonal flip is not equal to a rotation.
To have a PI/2 rotation you should flip the tile diagonally and then horizontally too.

Pseudocode:

    if (Diagonal && Horizontal) rotation = PI / 2;
    if (Horizontal && Vertical) rotation = PI;
    if (Vertical && Diagonal) rotation = 3/2 * PI;

**Comment by ironcutter24** [comment]
I posted an update on the development branch.
It needs some testing but for basic usage should work fine.

**Comment by ironcutter24** [comment]
I just posted an update that should solve the issue.
It covers all combinations of flipping supported by Tiled.

**Comment by icutter** [comment]
I just posted an update that solves the issue.
It covers all combinations of flipping supported by Tiled.

**Comment by TheLethalGoose** [comment]
Thanks!
